"""Create or refresh every lesson directory.

Usage::

    python tools/scaffold.py                 # write everything that is missing
    python tools/scaffold.py --only 1-50     # one slice of the course
    python tools/scaffold.py --force 013     # rewrite files even if they exist
    python tools/scaffold.py --report        # only show what is done and missing

Hand written lessons in ``tools/written`` always win. Everything else is
generated by :mod:`tools.synth`, so the whole course is runnable at once.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import curriculum
import synth
import templates
from lesson_model import STATUS_DRAFT, Lesson
from written import HANDWRITTEN

ROOT = Path(__file__).resolve().parent.parent
WELCOME = "000-welcome"


def parse_range(text: str) -> tuple[int, int]:
    """Return ``(start, end)`` for text such as ``1-50`` or ``13``.

    Args:
        text: The range to parse.

    Returns:
        The first and last lesson number to include.
    """
    if "-" in text:
        start, _, end = text.partition("-")
        return int(start), int(end)
    number = int(text)
    return number, number


def neighbours(number: int) -> tuple[str, str]:
    """Return the previous and next lesson folder names for a lesson.

    Args:
        number: The lesson number.

    Returns:
        The folder before and the folder after.
    """
    topics = curriculum.TOPICS
    before = WELCOME if number == 1 else topics[number - 2].folder
    after = topics[number].folder if number < len(topics) else ""
    return before, after


def files_for(topic: curriculum.Topic, lesson: Lesson) -> dict[str, str]:
    """Return every file a lesson directory should contain.

    Args:
        topic: The lesson's place in the course.
        lesson: The lesson content.

    Returns:
        A mapping of file name to file text.
    """
    before, after = neighbours(topic.number)
    section = next(item for item in curriculum.SECTIONS if item.key == topic.section)
    return {
        "README.md": templates.render_readme(topic, lesson, section.title, before, after),
        f"{topic.module}.py": lesson.source,
        f"{topic.test_module}.py": lesson.tests,
        "lesson.ipynb": templates.render_notebook(topic, lesson, before, after),
    }


def write(path: Path, text: str, force: bool) -> bool:
    """Write a file unless it already exists.

    Args:
        path: Where to write.
        text: What to write.
        force: Overwrite an existing file when true.

    Returns:
        ``True`` when the file was written.
    """
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def lesson_for(topic: curriculum.Topic) -> Lesson:
    """Return the best available lesson for a topic.

    Args:
        topic: The lesson's place in the course.

    Returns:
        A hand written lesson when one exists, otherwise a generated draft.
    """
    written = HANDWRITTEN.get(topic.number)
    return written if written is not None else synth.synthesize(topic)


def report(topics: tuple[curriculum.Topic, ...]) -> None:
    """Print how many lessons are hand written and how many are drafts."""
    written = [topic for topic in topics if topic.number in HANDWRITTEN]
    drafts = [topic for topic in topics if topic.number not in HANDWRITTEN]
    print(f"lessons in range : {len(topics)}")
    print(f"hand written     : {len(written)}")
    print(f"generated drafts : {len(drafts)}")
    if drafts:
        preview = ", ".join(topic.folder for topic in drafts[:8])
        print(f"first drafts     : {preview}{' ...' if len(drafts) > 8 else ''}")


def main(argv: list[str] | None = None) -> int:
    """Run the scaffolder.

    Args:
        argv: Command line arguments, defaulting to ``sys.argv[1:]``.

    Returns:
        The process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--only", default="1-999", help="lesson range such as 1-50")
    parser.add_argument("--force", default="", help="comma separated lesson numbers to rewrite")
    parser.add_argument("--report", action="store_true", help="only print the report")
    args = parser.parse_args(argv)

    start, end = parse_range(args.only)
    topics = tuple(topic for topic in curriculum.TOPICS if start <= topic.number <= end)
    if not topics:
        print(f"no lessons in range {args.only}")
        return 1

    if args.report:
        report(topics)
        return 0

    forced = {int(item) for item in args.force.split(",") if item.strip().isdigit()}
    force_all = args.force.strip() == "all"
    made = 0
    drafts = 0
    for topic in topics:
        lesson = lesson_for(topic)
        if lesson.status == STATUS_DRAFT:
            drafts += 1
        for name, text in files_for(topic, lesson).items():
            if write(ROOT / curriculum.lesson_dir(topic.number) / name, text, force_all or topic.number in forced):
                made += 1
    report(topics)
    print(f"files written    : {made}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
